"""session table

Revision ID: bcdd19b541b6
Revises: 
Create Date: 2024-01-17 03:26:53.331187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcdd19b541b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgsession',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('login_status', sa.String(), nullable=False),
    sa.Column('qr_login_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tgsession_pkey')),
    sa.UniqueConstraint('phone', name=op.f('tgsession_phone_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgsession')
    # ### end Alembic commands ###
